### ISSUE TITLE
Please explain what a TDU is

### ISSUE THREAD

**Issue by Beliavsky** [urbanjost/M_fixedform#1]
I am unfamiliar with the abbreviation.

**Comment by urbanjost** [comment]
Not surprising. Very CDC/NOS specific from long ago.  I actually found an on-line scanned copy of the manual describing TDU, PDU, CCL screen mode and some other things that shows not everything going forward is progress.  Screen interfaces were downright trivial compared to today from system shells and Fortran years ago. 

Hopefully, that clears up the nomenclature.  Now if I can just get around to finishing this or creating the OOP screen interface including simple graphics I keep saying I want to make :>
